#!/bin/zsh
# Installs a pseudo-localized language (xx) into the built app, so a walkthrough
# shows at a glance which strings are still hard-coded English.
#
#   VERSION=dev ./scripts/build-app.sh release
#   ./scripts/l10n-pseudo.sh
#   build/Knopo.app/Contents/MacOS/Knopo -AppleLanguages '(xx)'
#
# Values are accented and padded, so an untranslated string reads as plain
# English and a too-tight layout clips visibly.
set -e
cd "$(dirname "$0")/.."

APP="build/Knopo.app"
BASE="Localization/keys.txt"
OUT="build/pseudo/xx.lproj"

[[ -d "$APP" ]] || { echo "no $APP — run ./scripts/build-app.sh first" >&2; exit 1 }
[[ -f "$BASE" ]] || { echo "no $BASE — run ./scripts/l10n-extract.sh --update" >&2; exit 1 }

# Without a development region, the pseudo bundle becomes the fallback for every
# language: an English user would see accented text. Refuse rather than ship it.
if ! /usr/libexec/PlistBuddy -c "Print :CFBundleDevelopmentRegion" \
     "$APP/Contents/Info.plist" >/dev/null 2>&1; then
  echo "error: $APP has no CFBundleDevelopmentRegion; the pseudo language would" >&2
  echo "       become the fallback for English too. Fix scripts/build-app.sh." >&2
  exit 1
fi

rm -rf build/pseudo
mkdir -p "$OUT"

APP="$APP" BASE="$BASE" OUT="$OUT" python3 - <<'PY'
import os, plistlib, re

app, base, out = os.environ["APP"], os.environ["BASE"], os.environ["OUT"]

ACCENTS = str.maketrans(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "àƀçðéƒĝĥïĵķĺɱñôþɋŕšţùᶌŵҳýž"
    "ÀƁÇÐÉƑĜĤÏĴĶĹⱮÑÔÞɊŔŠŢÙᶌŴҲÝŽ",
)
# Everything the formatter owns: %lld, %@, %2$lld, %1$#@name@ …
SPEC = re.compile(r"%(?:\d+\$)?(?:#@[A-Za-z0-9_]+@|lld|ld|[@dsf])")

def accent(text):
    parts, last = [], 0
    for m in SPEC.finditer(text):
        parts.append(text[last:m.start()].translate(ACCENTS))
        parts.append(m.group(0))
        last = m.end()
    parts.append(text[last:].translate(ACCENTS))
    return "".join(parts)

DASH = "\u2014"

def pad(text):
    """Brackets make truncation obvious; the dashes simulate a longer language."""
    return "[" + text + DASH * max(2, round(len(text) * 0.3)) + "]"

def quote(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')

# The baseline is grouped into [Table] sections.
keys, table, skip = {}, "Localizable", False
for line in open(base).read().splitlines():
    if not line or line.startswith("#"):
        continue
    if line.startswith("[") and line.endswith("]"):
        name = line[1:-1]
        skip = name.endswith(":plurals")   # repeats keys listed above
        table = name[:-len(":plurals")] if skip else name
    elif not skip:
        keys.setdefault(table, []).append(line.partition("\t")[0])

def pseudo_plurals(src_path):
    """Accent the variants; bracket and pad only the composed format."""
    result = {}
    for key, entry in plistlib.load(open(src_path, "rb")).items():
        copy = {}
        for name, value in entry.items():
            if name == "NSStringLocalizedFormatKey":
                copy[name] = pad(accent(value))
            elif isinstance(value, dict):
                fixed = ("NSStringFormatSpecTypeKey", "NSStringFormatValueTypeKey")
                copy[name] = {k: (v if k in fixed else accent(v)) for k, v in value.items()}
            else:
                copy[name] = value
        result[key] = copy
    return result

plain = plurals = 0
for table, table_keys in keys.items():
    # A plural key must live only in the .stringsdict; a .strings entry for the
    # same key would shadow it.
    src_dict = f"Localization/en.lproj/{table}.stringsdict"
    pseudo_dict = pseudo_plurals(src_dict) if os.path.exists(src_dict) else {}
    if pseudo_dict:
        plistlib.dump(pseudo_dict, open(f"{out}/{table}.stringsdict", "wb"))
        plurals += len(pseudo_dict)
    with open(f"{out}/{table}.strings", "w") as f:
        f.write("/* Pseudo-localized. Generated by scripts/l10n-pseudo.sh. */\n")
        for k in table_keys:
            if k in pseudo_dict:
                continue
            f.write(f'"{quote(k)}" = "{quote(pad(accent(k)))}";\n')
            plain += 1

# NSHumanReadableCopyright shows in the About panel and is unreachable from
# Swift, so it only ever localizes through InfoPlist.strings.
info = plistlib.load(open(f"{app}/Contents/Info.plist", "rb"))
with open(f"{out}/InfoPlist.strings", "w") as f:
    f.write("/* Pseudo-localized. Generated by scripts/l10n-pseudo.sh. */\n")
    if notice := info.get("NSHumanReadableCopyright"):
        f.write(f'"NSHumanReadableCopyright" = "{quote(pad(accent(notice)))}";\n')

print(f"{plain} strings + {plurals} plural entries pseudo-localized "
      f"across {len(keys)} table(s)")
PY

for f in "$OUT"/*; do plutil -lint "$f" >/dev/null; done
cp -R "$OUT" "$APP/Contents/Resources/"
# Resources changed after build-app.sh signed the bundle, so re-seal it.
codesign --force --sign - "$APP" >/dev/null 2>&1
codesign --verify --deep "$APP"

echo "Installed xx.lproj into $APP"
echo "  $APP/Contents/MacOS/Knopo -AppleLanguages '(xx)'"
echo "Anything still in plain English is an unextracted string."
